### ISSUE TITLE
Cannot create virtualenv

### ISSUE THREAD

**Issue by mcdevitts** [pdm-project/pdm-venv#18]
With a fresh install of pdm and pdm-venv (installed and injected via pipx), I cannot create virtual environments.

Running:
![image](https://user-images.githubusercontent.com/13813076/130336389-3cb9a9c9-2041-4adc-ab2c-cfe72b7ba984.png)

pdm version: 1.8.0 
pdm-venv version: 0.3.0
Python version: 3.7
OS: Windows

I wish I had more to report, but I hit a brick wall and the verbose option doesn't provide more insight. Let me know what else would help to debug this issue.

**Comment by frostming** [comment]
I can't reproduce. Can you try to expose the verbose error information by any means? If `--verbose` doesn't work, try modifying the code under `pdm/core.py`

**Comment by mcdevitts** [comment]
Running a slightly different version of the command, I at least get the same error with a traceback:
`
$ pdm venv create --verbose                                                                                                       
Run command: ['C:\\Users\\smcdevitt\\.local\\pipx\\venvs\\pdm\\Scripts\\python.exe', '-m', 'virtualenv', WindowsPath('C:/Users/smc
devitt/AppData/Local/pdm/pdm/venvs/pdm_test4-gmpp_fe3-3.7'), '-p', 'C:/Users/smcdevitt/AppData/Local/Programs/Python/Python37/pyth
on.EXE']                                                                                                                          
Traceback (most recent call last):                                                                                                
  File "c:\users\smcdevitt\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main                 
    "__main__", mod_spec)                                                                                                         
  File "c:\users\smcdevitt\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code                            
    exec(code, run_globals)                                                                                                       
  File "c:\users\smcdevitt\.local\bin\pdm.exe\__main__.py", line 7, in <module>                                                   
  File "C:\Users\smcdevitt\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 195, in main                                
    return Core().main(args)                                                                                                      
  File "C:\Users\smcdevitt\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 153, in main                                
    raise cast(Exception, err).with_traceback(traceback)                                                                          
  File "C:\Users\smcdevitt\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 148, in main                                
    f(options.project, options)                                                                                                   
  File "C:\Users\smcdevitt\.local\pipx\venvs\pdm\lib\site-packages\pdm_venv\commands\create.py", line 50, in handle               
    path = venv_backend.create(options.name, options.venv_args, options.force)                                                    
  File "C:\Users\smcdevitt\.local\pipx\venvs\pdm\lib\site-packages\pdm_venv\backends.py", line 75, in create                      
    self.perform_create(location, args)                                                                                           
  File "C:\Users\smcdevitt\.local\pipx\venvs\pdm\lib\site-packages\pdm_venv\backends.py", line 88, in perform_create              
    self.subprocess_call(cmd)                                                                                                     
  File "C:\Users\smcdevitt\.local\pipx\venvs\pdm\lib\site-packages\pdm_venv\backends.py", line 50, in subprocess_call             
    subprocess.check_call(cmd)                                                                                                    
  File "c:\users\smcdevitt\appdata\local\programs\python\python37\lib\subprocess.py", line 358, in check_call                     
    retcode = call(*popenargs, **kwargs)                                                                                          
  File "c:\users\smcdevitt\appdata\local\programs\python\python37\lib\subprocess.py", line 339, in call                           
    with Popen(*popenargs, **kwargs) as p:                                                                                        
  File "c:\users\smcdevitt\appdata\local\programs\python\python37\lib\subprocess.py", line 800, in __init__                       
    restore_signals, start_new_session)                                                                                           
  File "c:\users\smcdevitt\appdata\local\programs\python\python37\lib\subprocess.py", line 1148, in _execute_child                
    args = list2cmdline(args)                                                                                                     
  File "c:\users\smcdevitt\appdata\local\programs\python\python37\lib\subprocess.py", line 555, in list2cmdline                   
    needquote = (" " in arg) or ("\t" in arg) or not arg                                                                          
TypeError: argument of type 'WindowsPath' is not iterable
`

**Comment by frostming** [comment]
Nice, that is helpful, fixing it.
